spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.21.129:3306/mall_sms
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: mall-coupon

mybatis-plus:
  #主键自增长
  global-config:
    db-config:
      id-type: auto

server:
  port: 7000
