spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.21.129:3306/mall_pms
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: mall-product

mybatis-plus:
  #主键自增长
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 10000

